name: 'build' 
on: # rebuild only when devcontainer files change
  pull_request:
    paths:
      - '.github/.devcontainer/**'
  push:
    branches:
      - main
    paths:
      - '.github/.devcontainer/**'

# Add permissions block
permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          subFolder: .github
          imageName: ghcr.io/${{ github.repository_owner }}/udw-devcontainer
          cacheFrom: ghcr.io/${{ github.repository_owner }}/udw-devcontainer
          push: always